stages:
  - build
  - deploy

variables:
  REACT_APP_INVENTORY_API: https://${HEROKU_INVENTORY_API_APP}.herokuapp.com
  REACT_APP_SALES_API: https://${HEROKU_SALES_API_APP}.herokuapp.com
  REACT_APP_SERVICE_API: https://${HEROKU_SERVICE_API_APP}.herokuapp.com


build-inventory-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - cd inventory/api
    - docker build -t ${CI_REGISTRY_IMAGE}/inventory_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/inventory_api:latest ${CI_REGISTRY_IMAGE}/inventory_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/inventory_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/inventory_api:latest


build-sales-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - cd sales/api
    - docker build -t ${CI_REGISTRY_IMAGE}/sales_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/sales_api:latest ${CI_REGISTRY_IMAGE}/sales_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/sales_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/sales_api:latest


build-sales-poll-image-job:
  rules:
    - if: ($CI_COMMIT_BRANCH == "deploy" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd sales
    - docker build -t ${CI_REGISTRY_IMAGE}/sales_poller:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/sales_poller:latest ${CI_REGISTRY_IMAGE}/sales_poller:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/sales_poller:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/sales_poller:latest

  
build-service-api-image-job:
  rules:
    - if: ($CI_COMMIT_BRANCH == "deploy" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd service/api
    - docker build -t ${CI_REGISTRY_IMAGE}/service_api:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/service_api:latest ${CI_REGISTRY_IMAGE}/service_api:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/service_api:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/service_api:latest


build-service-poll-image-job:
  rules:
    - if: ($CI_COMMIT_BRANCH == "deploy" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd service
    - docker build -t ${CI_REGISTRY_IMAGE}/service_poller:latest .
    - docker tag ${CI_REGISTRY_IMAGE}/service_poller:latest ${CI_REGISTRY_IMAGE}/service_poller:$CI_JOB_ID
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push ${CI_REGISTRY_IMAGE}/service_poller:$CI_JOB_ID
    - docker push ${CI_REGISTRY_IMAGE}/service_poller:latest


build-front-end-job:
  stage: build
  image: node:lts-bullseye
  variables:
    PUBLIC_URL: https://maryamckinnon.gitlab.io/project-beta
  script:
    - cd ghi/app
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/app/build/


pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/app/build/ public
  artifacts:
    paths:
      - public


deploy-inventory-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-inventory-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/inventory_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/inventory_api:latest registry.heroku.com/$HEROKU_INVENTORY_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_INVENTORY_API_APP/web:latest

deploy-sales-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-sales-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/sales_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/sales_api:latest registry.heroku.com/$HEROKU_SALES_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_SALES_API_APP/web:latest

deploy-sales-poll-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-sales-poll-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/sales_poller:latest
    - docker tag ${CI_REGISTRY_IMAGE}/sales_poller:latest registry.heroku.com/$HEROKU_SALES_POLLER_APP/worker:latest
    - docker push registry.heroku.com/$HEROKU_SALES_POLLER_APP/worker:latest

deploy-service-api-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-service-api-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/service_api:latest
    - docker tag ${CI_REGISTRY_IMAGE}/service_api:latest registry.heroku.com/$HEROKU_SERVICE_API_APP/web:latest
    - docker push registry.heroku.com/$HEROKU_SERVICE_API_APP/web:latest

deploy-service-poll-image-job:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: deploy
  image: docker:20.10.16
  needs:
    - build-service-poll-image-job
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker pull ${CI_REGISTRY_IMAGE}/service_poller:latest
    - docker tag ${CI_REGISTRY_IMAGE}/service_poller:latest registry.heroku.com/$HEROKU_SERVICE_POLLER_APP/worker:latest
    - docker push registry.heroku.com/$HEROKU_SERVICE_POLLER_APP/worker:latest

release-inventory-api-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-inventory-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_INVENTORY_API_APP

release-sales-api-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-sales-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_SALES_API_APP

release-sales-poll-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-sales-poll-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release worker --app $HEROKU_SALES_POLLER_APP


release-service-api-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-service-api-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release web --app $HEROKU_SERVICE_API_APP

release-service-poll-image-job:
  stage: deploy
  image: node:10.17-alpine
  needs:
    - deploy-service-poll-image-job
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - apk add curl bash
    - curl https://cli-assets.heroku.com/install.sh | sh
  script:
    - heroku container:release worker --app $HEROKU_SERVICE_POLLER_APP
