# Generated by Django 4.0.3 on 2022-06-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_status_alter_appointment_technician_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',), 'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
