# Generated by Django 4.0.3 on 2022-06-22 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status_alter_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
