# Generated by Django 4.0.3 on 2022-10-06 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("picture_url", models.URLField()),
                (
                    "price",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="inventory_rest.manufacturer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Automobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("year", models.PositiveSmallIntegerField()),
                ("vin", models.CharField(max_length=17, unique=True)),
                ("sold", models.BooleanField(default=False)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automobiles",
                        to="inventory_rest.vehiclemodel",
                    ),
                ),
            ],
        ),
    ]
